### ISSUE TITLE
Kernal Panic Crash PI on Receive packet over MTU

### ISSUE THREAD

**Issue by lowerpower** [mechatrax/4gpi#40]
Adapter is set for MTU of 1430, if a packet comes in from WAN that is larger, a kernel panic happens and raspbery pi reboots.

アダプタは MTU 1430 に設定されており、パケットが WAN から入ってくると、カーネルパニックが発生し、raspbery pi が再起動します。

**Comment by mechatrax-kiyonaga** [comment]
Thanks for reporting the issue.
Please let me know the kernel panic message and OS version.

**Comment by lowerpower** [comment]
Linux raspberrypi 5.10.103-v7+ #1529 SMP Tue Mar 8 12:21:37 GMT 2022 armv7l

demo@raspberrypi:~ $ cat /etc/os-release 
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster

wwan0: flags=4305<UP,POINTOPOINT,RUNNING,NOARP,MULTICAST>  mtu 1420
        inet 100.70.210.205  netmask 255.255.255.252  destination 100.70.210.205
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 1000  (UNSPEC)
        RX packets 25395  bytes 1702023 (1.6 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 101857  bytes 4189442 (3.9 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

If the pi comes back up I will get the panic message

**Comment by lowerpower** [comment]
Here is a test server you can use, run it on an amazon AMI or some other remote server:
https://github.com/lowerpower/UDP_MTU_Checker

Then request a 1460 byte packet from the server from the the pi that has a 4gpi wan and the pi will crash and reboot.

**Comment by mechatrax-kiyonaga** [comment]
Thanks for sharing the OS version and UDP_MTU_Checker.
Now I can reproduce the issue.
I'll analyze this, but I need some time.

**Comment by mechatrax-kiyonaga** [comment]
Please use 4gpi-bullseye-lite-armhf-20220928.
https://mechatrax.com/data/4gpi/4gpi-bullseye-lite-armhf-20220928.img.xz
This issue is probably caused by a bug in kernel 5.10.
It does not occur when running on kernel 5.15.
This OS image uses kernel 5.15.
Thank you.

**Comment by lowerpower** [comment]
Thanks!  will check it out.

**Comment by lowerpower** [comment]
Seems to fix the issue
