### ISSUE TITLE
イメージファイルが壊れている

### ISSUE THREAD

**Issue by namnam0610** [mechatrax/4gpi#8]
https://mechatrax.com/data/4gpi/　からイメージファイル（4gpi-buster-lite-20191120.zip
4gpi-buster-lite-20190820.zip)をダウンロードしてから、isoファイルが壊れているメッセージが出ます。ご確認をお願い致します。

**Comment by m-honda** [comment]
ダウンロードした .zip ファイルが壊れていないかハッシュ値を確認してください。
ハッシュ値はリリースノートを参照してください。
https://github.com/mechatrax/4gpi/tree/master/os

また、4GPi のイメージファイルは ZIP64 フォーマットで圧縮されています。
.zip をダウンロードした後、.img を展開してから SD へ書き込みを行ってください。
うまく展開できない場合は raspberrypi.org のインストールガイドを参考に、対応したツールを使用して .zip ファイルを展開してから書き込みを行ってください。
https://www.raspberrypi.org/documentation/installation/installing-images/README.md

ご確認の程よろしくお願い申し上げます。

**Comment by m-honda** [comment]
4gpi-buster-lite-20200612 では圧縮ファイルを通常の ZIP フォーマットに変更しました。
Raspberry Pi Imager v1.3 を使用して圧縮ファイルの状態で SD カードへの書き込みを確認しています。

本件はクローズしたいと思います。
問題がありましたら再度コメントをお願い致します。
